### ISSUE TITLE
Recent Breaking Change - EXPOSE 8000/Publish-all

### ISSUE THREAD

**Issue by Druotic** [cnadiminti/docker-dynamodb-local#5]
This is more for informational purposes for others, but there was a recent breaking change [here](https://github.com/cnadiminti/docker-dynamodb-local/commit/47934a15502faed049020a13a26954afb50344b5#diff-3254677a7917c6c01f55212f86c57fbf) that I don't think was intended to be a breaking change. For consumers of this image that use docker run's `--publish-all/-P` option, port 8000 is no longer published with the latest changes. The port has to be explicitly published now, instead of relying on the default EXPOSE port.

**Comment by mchristiansen** [comment]
Out of curiosity, was this addressed and was it confirmed the breaking change was intentional? [Best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#expose) is to expose the "common default port your application runs on", which in this case is 8000. I think the original Dockerfile allowed for the port to be changed already by overriding the command, so I don't think this change was really necessary.

**Comment by Druotic** [comment]
Not that I'm aware of - I only closed the issue because it has been over a month with no response/acknowledgement. I assumed no one had any intention to address the issue and/or not many people were bitten by the issue.

I'm happy to reopen if it's something people care about.

**Comment by mchristiansen** [comment]
It looks like the change was ported to the different versions and published [yesterday](https://github.com/cnadiminti/docker-dynamodb-local/commit/88dcc1aed99fb167a2f3536860cf74f087756c0e), so maybe more people will care now. I wound up here because it broke my build.

**Comment by cnadiminti** [comment]
First of all, sorry for the late response. I was on month+ long vacation.

@Druotic Thanks for bringing it up. 
@mchristiansen Thanks for your inputs. 

I agree that `EXPOSE 8000` should be in Dockerfile. The [original change](https://github.com/cnadiminti/docker-dynamodb-local/commit/47934a15502faed049020a13a26954afb50344b5#diff-3254677a7917c6c01f55212f86c57fbf) went in without documentation also. I'll fix it soon.

I'm curious to know your use case that relies on `--publish-all/-P`.

**Comment by cnadiminti** [comment]
It should all be good now. Please take a look at the [fix](https://github.com/cnadiminti/docker-dynamodb-local/commit/503d85d9b487de0b2c6a53e1604af57961481317), validate and confirm.

**Comment by mchristiansen** [comment]
Fix looks good to me. Thank you for looking at this.

I am using the docker-java library to create containers to use during testing. After some digging I found [an issue](https://github.com/docker-java/docker-java/issues/238) that pointed out that the docker-java library forces you to explicitly declare exposed ports not included in the image, so I was inadvertently dependent on the image declaring the exposed port. For whatever reason this is different behavior than if you just use the command line `-p` option, which does it automatically.

Adding the explicit exposed ports to the create container command fixed my problem, but I thought it worth bringing up since it seemed better for it to be there in the image as well.

**Comment by cnadiminti** [comment]
Thanks for the confirmation.

Got it. Thanks for the explanation.
